### ISSUE TITLE
windwos  anaconda  install failed?

### ISSUE THREAD

**Issue by zuowanbushiwo** [Rikorose/DeepFilterNet#103]
@Rikorose 
       Thanks，This is a very good project. I use the web demo to test ，and the results is very good, but my local installation fails. I use the anaconda environment. how to filxed?

      
`(pytorch36) C:\Users\admin>pip install deepfilternet`
```
 ERROR: Cannot install deepfilternet==0.1.2, deepfilternet==0.1.3 and deepfilternet==0.1.4 because these package versions have conflicting dependencies.

The conflict is caused by:
    deepfilternet 0.1.4 depends on DeepFilterLib<0.2 and >=0.1
    deepfilternet 0.1.3 depends on DeepFilterLib<0.2 and >=0.1
    deepfilternet 0.1.2 depends on DeepFilterLib<0.2 and >=0.1

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict
```
`(pytorch36) C:\Users\admin>pip install DeepFilterLib`
```
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
ERROR: Could not find a version that satisfies the requirement DeepFilterLib(from versions: none)
ERROR: No matching distribution found for DeepFilterLib
```

```
(pytorch36) C:\Users\admin>conda list
# packages in environment at D:\ProgramData\miniconda3\envs\pytorch36:
#
# Name                    Version                   Build  Channel
absl-py                   1.1.0                    pypi_0    pypi
appdirs                   1.4.4                    pypi_0    pypi
attrs                     21.4.0                   pypi_0    pypi
audioread                 2.1.9                    pypi_0    pypi
blas                      2.111                       mkl    conda-forge
blas-devel                3.9.0              11_win64_mkl    conda-forge
ca-certificates           2022.5.18.1          h5b45459_0    conda-forge
cachetools                4.2.4                    pypi_0    pypi
certifi                   2022.5.18.1              pypi_0    pypi
cffi                      1.15.0                   pypi_0    pypi
charset-normalizer        2.0.12                   pypi_0    pypi
colorama                  0.4.4                    pypi_0    pypi
cudatoolkit               11.1.1               heb2d755_7    conda-forge
cycler                    0.10.0                   py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
cython                    0.29.30                  pypi_0    pypi
dataclasses               0.8                pyh787bdff_2    conda-forge
decorator                 4.4.2                    pypi_0    pypi
ear                       2.1.0                    pypi_0    pypi
flatbuffers               2.0                      pypi_0    pypi
freetype                  2.10.4               h546665d_1    conda-forge
google-auth               2.7.0                    pypi_0    pypi
google-auth-oauthlib      0.4.6                    pypi_0    pypi
grpcio                    1.46.3                   pypi_0    pypi
icu                       68.1                 h0e60522_0    conda-forge
idna                      3.3                      pypi_0    pypi
imageio                   2.15.0                   pypi_0    pypi
importlib-metadata        4.8.3                    pypi_0    pypi
importlib-resources       5.4.0                    pypi_0    pypi
intel-openmp              2021.3.0          h57928b3_3372    conda-forge
jbig                      2.1               h8d14728_2003    conda-forge
joblib                    1.1.0                    pypi_0    pypi
jpeg                      9d                   h8ffe710_0    conda-forge
kiwisolver                1.3.1            py36he95197e_1    conda-forge
lcms2                     2.12                 h2a16943_0    conda-forge
lerc                      2.2.1                h0e60522_0    conda-forge
libblas                   3.9.0              11_win64_mkl    conda-forge
libcblas                  3.9.0              11_win64_mkl    conda-forge
libclang                  11.1.0          default_h5c34c98_1    conda-forge
libdeflate                1.7                  h8ffe710_5    conda-forge
liblapack                 3.9.0              11_win64_mkl    conda-forge
liblapacke                3.9.0              11_win64_mkl    conda-forge
libpng                    1.6.37               h1d00b33_2    conda-forge
libprotobuf               3.18.0               h7755175_1    conda-forge
librosa                   0.9.1                    pypi_0    pypi
libtiff                   4.3.0                h0c97f57_1    conda-forge
libuv                     1.42.0               h8ffe710_0    conda-forge
llvmlite                  0.36.0                   pypi_0    pypi
lxml                      4.9.0                    pypi_0    pypi
lz4-c                     1.9.3                h8ffe710_1    conda-forge
m2w64-gcc-libgfortran     5.3.0                         6    conda-forge
m2w64-gcc-libs            5.3.0                         7    conda-forge
m2w64-gcc-libs-core       5.3.0                         7    conda-forge
m2w64-gmp                 6.1.0                         2    conda-forge
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    conda-forge
markdown                  3.3.7                    pypi_0    pypi
matplotlib                3.3.1                         1    conda-forge
matplotlib-base           3.3.1            py36h856a30b_0    conda-forge
mkl                       2021.3.0           hb70f87d_564    conda-forge
mkl-devel                 2021.3.0           h57928b3_565    conda-forge
mkl-include               2021.3.0           hb70f87d_564    conda-forge
msys2-conda-epoch         20160418                      1    conda-forge
multipledispatch          0.6.0                    pypi_0    pypi
networkx                  2.5.1                    pypi_0    pypi
ninja                     1.10.2               h5362a0b_0    conda-forge
numba                     0.53.1                   pypi_0    pypi
numpy                     1.19.5           py36h4b40d73_2    conda-forge
oauthlib                  3.2.0                    pypi_0    pypi
olefile                   0.46               pyh9f0ad1d_1    conda-forge
onnx                      1.10.1           py36h524f2fb_1    conda-forge
onnxruntime               1.10.0                   pypi_0    pypi
openjpeg                  2.4.0                hb211442_1    conda-forge
openssl                   1.1.1o               h8ffe710_0    conda-forge
packaging                 21.3                     pypi_0    pypi
pandas                    1.1.5                    pypi_0    pypi
pesq                      0.0.4                    pypi_0    pypi
pillow                    8.3.2            py36h10c25d6_0    conda-forge
pip                       21.3.1                   pypi_0    pypi
pooch                     1.6.0                    pypi_0    pypi
prettytable               2.5.0                    pypi_0    pypi
protobuf                  3.19.4                   pypi_0    pypi
pyasn1                    0.4.8                    pypi_0    pypi
pyasn1-modules            0.2.8                    pypi_0    pypi
pycparser                 2.21                     pypi_0    pypi
pyparsing                 2.2.0                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
pypesq                    1.2.4                    pypi_0    pypi
pyqt                      5.12.3           py36ha15d459_7    conda-forge
pyqt-impl                 5.12.3           py36he2d232f_7    conda-forge
pyqt5-sip                 4.19.18          py36he2d232f_7    conda-forge
pyqtchart                 5.12             py36he2d232f_7    conda-forge
pyqtwebengine             5.12.1           py36he2d232f_7    conda-forge
pystoi                    0.3.3                    pypi_0    pypi
pytest-runner             5.3.2                    pypi_0    pypi
python                    3.6.13          h39d44d4_2_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python_abi                3.6                     2_cp36m    conda-forge
pytorch                   1.9.1           py3.6_cuda11.1_cudnn8_0    pytorch
pytz                      2022.1                   pypi_0    pypi
pyvad                     0.1.3                    pypi_0    pypi
pywavelets                1.1.1                    pypi_0    pypi
qt                        5.12.9               h5909a2a_4    conda-forge
requests                  2.27.1                   pypi_0    pypi
requests-oauthlib         1.3.1                    pypi_0    pypi
resampy                   0.2.2                    pypi_0    pypi
rsa                       4.8                      pypi_0    pypi
ruamel-yaml               0.17.21                  pypi_0    pypi
ruamel-yaml-clib          0.2.6                    pypi_0    pypi
scikit-image              0.17.2                   pypi_0    pypi
scikit-learn              0.24.2                   pypi_0    pypi
scipy                     1.5.4                    pypi_0    pypi
setuptools                59.5.0                   pypi_0    pypi
six                       1.16.0             pyh6c4a22f_0    conda-forge
soundfile                 0.10.3.post1             pypi_0    pypi
speechpy                  2.4                      pypi_0    pypi
sqlite                    3.36.0               h8ffe710_1    conda-forge
tbb                       2021.3.0             h2d74725_0    conda-forge
tensorboard               2.9.1                    pypi_0    pypi
tensorboard-data-server   0.6.1                    pypi_0    pypi
tensorboard-plugin-wit    1.8.1                    pypi_0    pypi
threadpoolctl             3.1.0                    pypi_0    pypi
tifffile                  2020.9.3                 pypi_0    pypi
tk                        8.6.11               h8ffe710_1    conda-forge
torchaudio                0.9.1                      py36    pytorch
torchvision               0.2.2                      py_3    pytorch
tornado                   4.5.2                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
tqdm                      4.64.0                   pypi_0    pypi
typing-extensions         3.10.0.2             hd8ed1ab_0    conda-forge
typing_extensions         3.10.0.2           pyha770c72_0    conda-forge
ucrt                      10.0.20348.0         h57928b3_0    conda-forge
urllib3                   1.26.9                   pypi_0    pypi
vc                        14.2                 hb210afc_5    conda-forge
vs2015_runtime            14.29.30037          h902a5da_5    conda-forge
wavinfo                   1.6.3                    pypi_0    pypi
wcwidth                   0.2.5                    pypi_0    pypi
webrtcvad                 2.0.10                   pypi_0    pypi
werkzeug                  2.0.3                    pypi_0    pypi
wheel                     0.29.0                   py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
wincertstore              0.2                      py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
xz                        5.2.5                h62dcd97_1    conda-forge
zipp                      3.6.0                    pypi_0    pypi
zlib                      1.2.11            h62dcd97_1010    conda-forge
zstd                      1.5.0                h6255e5f_0    conda-forge
```

**Comment by zuowanbushiwo** [comment]
@Rikorose 
The above error can be solved by upgrading to python3.9, because deepfilterlib does not have a version of python3.6

I have another problem：

```
(DeepFilterNet) C:\Users\admin\Desktop\DeepFilterNet2\mynoisy>deepFilter demo_input_fileid_1.wav  --output-dir  C:\Users\admin\Desktop\DeepFilterNet2
Traceback (most recent call last):
  File "d:\programdata\miniconda3\envs\deepfilternet\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "d:\programdata\miniconda3\envs\deepfilternet\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\ProgramData\miniconda3\envs\DeepFilterNet\Scripts\deepFilter.exe\__main__.py", line 7, in <module>
  File "d:\programdata\miniconda3\envs\deepfilternet\lib\site-packages\df\enhance.py", line 329, in run
    main(parser.parse_args())
  File "d:\programdata\miniconda3\envs\deepfilternet\lib\site-packages\df\enhance.py", line 26, in main
    model, df_state, suffix = init_df(
  File "d:\programdata\miniconda3\envs\deepfilternet\lib\site-packages\df\enhance.py", line 101, in init_df
    model_base_dir = os.path.relpath(
  File "d:\programdata\miniconda3\envs\deepfilternet\lib\ntpath.py", line 703, in relpath
    raise ValueError("path is on mount %r, start on mount %r" % (
ValueError: path is on mount 'd:', start on mount 'C:
```
The test file cannot be placed in the C drive, I  put it in the D drive，then  it run ok.    I don't know if this is a bug.

Thanks!

**Comment by Rikorose** [comment]
Hi thanks for your interest in DeepFilterNet. There are currently some issues related to windows. Since I don't have a windows machine it's always hard to debug those issues. I would highly appreciate patches that fix windows usage.

**Comment by zuowanbushiwo** [comment]
thanks，if i  can  fix this， i will submit a PR.
