### ISSUE TITLE
Unable to run deepFIlter form CLI

### ISSUE THREAD

**Issue by Anand195** [Rikorose/DeepFilterNet#118]
Hi guys, 
I have followed the installation instruction using pip and now I'm stuck with SLURM and I don't know how to fix it

I'm executing deepfilternet from colab pro+ account.

Here is the issue.

Traceback (most recent call last):
  File "/usr/local/bin/deepFilter", line 5, in <module>
    from df.enhance import run
  File "/usr/local/lib/python3.7/dist-packages/df/enhance.py", line 18, in <module>
    from df.logger import init_logger, warn_once
  File "/usr/local/lib/python3.7/dist-packages/df/logger.py", line 49
    if (jobid := os.getenv("SLURM_JOB_ID")) is not None:
              ^
SyntaxError: invalid syntax

This is which I get while trying to execute this :-> !deepFilter /content/test_audio_053830.wav --output-dir /content

Anyone got into this kind of issue??

DO let me know the solution / how can I run this.

**Comment by Rikorose** [comment]
Which python version are you using? I guess the if assign syntax may not be supported by your python version.

**Comment by Anand195** [comment]
I'm using python 3.9

**Comment by dtx525942103** [comment]
i meet the same error, which python should use

**Comment by Rikorose** [comment]
This is an if assign expression (PEP 572) and supported by python 3.8 and higher. This should work with python 3.9 and is tested with CI with python 3.8 - 3.10.

@Anand195 when running this via codelab, I suggest to directly call the api within enhance.py directly from python.

**Comment by Anand195** [comment]
> 

Thanks for the such an informative reply.
It would be great it you share an example to tun this API directly from CLI.

**Comment by Rikorose** [comment]
If you want to run from CLI, you can either use `deepFilter /content/test_audio_053830.wav --output-dir /content` when installed via pip. Or you can clone the repository and call the enhance script: `python DeepFilterNet/df/enhance.py /content/test_audio_053830.wav --output-dir /content`

**Comment by Anand195** [comment]
> If you want to run from CLI, you can either use `deepFilter /content/test_audio_053830.wav --output-dir /content` when installed via pip. Or you can clone the repository and call the enhance script: `python DeepFilterNet/df/enhance.py /content/test_audio_053830.wav --output-dir /content`

After satisfying all the requirements I'm getting the error

ModuleNotFoundError: No module named 'libdf'

Can't find pip package for this

**Comment by Rikorose** [comment]
Please try `pip install deepfilterlib` or follow the instructions on the readme.

**Comment by Anand195** [comment]
> Please try `pip install deepfilterlib` or follow the instructions on the readme.

I have followed your instructions as well checked the ReadMe file , got into this error.

    from io import load_audio, resample, save_audio
ImportError: cannot import name 'load_audio' from 'io' 

also tried to solve this by myself, unfortunately can't find any library that can satisfy this error.

**Comment by Rikorose** [comment]
here is the io file: https://github.com/Rikorose/DeepFilterNet/blob/main/DeepFilterNet/df/io.py#L15

not sure what you are doing

**Comment by Anand195** [comment]
> here is the io file: https://github.com/Rikorose/DeepFilterNet/blob/main/DeepFilterNet/df/io.py#L15
> 
> not sure what you are doing

Followed your reply and sendup with this situation 
Don't know how to get rid of this

(venv) 192:df caypro$ python3 enhance.py /Users/caypro/Downloads/drive-download-20220729T062801Z-001/3471_9849_20210807_060527.wav --output-dir /Users/caypro/Anand
2022-08-23 13:47:34 | INFO     | DF | Running on torch 1.12.0
2022-08-23 13:47:34 | INFO     | DF | Running on host 192.168.1.9
fatal: not a git repository (or any of the parent directories): .git
Traceback (most recent call last):
  File "/Users/caypro/Anand/project/DeepFilterNet-main/DeepFilterNet/df/enhance.py", line 291, in <module>
    run()
  File "/Users/caypro/Anand/project/DeepFilterNet-main/DeepFilterNet/df/enhance.py", line 287, in run
    main(parser.parse_args())
  File "/Users/caypro/Anand/project/DeepFilterNet-main/DeepFilterNet/df/enhance.py", line 24, in main
    model, df_state, suffix = init_df(
  File "/Users/caypro/Anand/project/DeepFilterNet-main/DeepFilterNet/df/enhance.py", line 104, in init_df
    init_logger(file=log_file, level=log_level, model=model_base_dir)
  File "/Users/caypro/Anand/project/DeepFilterNet-main/DeepFilterNet/df/logger.py", line 46, in init_logger
    commit = get_commit_hash()
  File "/Users/caypro/Anand/project/DeepFilterNet-main/DeepFilterNet/df/utils.py", line 155, in get_commit_hash
    commit = subprocess.check_output(args).strip().decode()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 1754, in _execute_child
    self.pid = _posixsubprocess.fork_exec(
TypeError: expected str, bytes or os.PathLike object, not NoneType

kindly go through and do let me know the possible solutions.

**Comment by Rikorose** [comment]
Thanks for this backtrace. This is a bug and a fix will be included in the next release.

**Comment by Anand195** [comment]
Thanks, Will wait for the upcoming release with fix.
