### ISSUE TITLE
RuntimeError: Expected canUse32BitIndexMath(input) && canUse32BitIndexMath(output) to be true, but got false. 

### ISSUE THREAD

**Issue by youssefabdelm** [Rikorose/DeepFilterNet#121]
Hey! I tried to run this model on an A6000 and A100 using a GPU cloud provider. However I noticed something interesting. The reason I was trying to use these GPUs is because I wanted to run on much longer audio files. I found I was able to do this up to around the 50 minute mark. Above approx. an hour, I get this error: 
```
2022-07-30 16:34:06 | INFO     | DF | Running on torch 1.12.0
2022-07-30 16:34:06 | INFO     | DF | Running on host a170e9560a44
fatal: not a git repository (or any of the parent directories): .git
2022-07-30 16:34:06 | INFO     | DF | Loading model settings of DeepFilterNet2
2022-07-30 16:34:06 | INFO     | DF | Using DeepFilterNet2 model at ../opt/conda/lib/python3.7/site-packages/pretrained_models/DeepFilterNet2
2022-07-30 16:34:06 | INFO     | DF | Initializing model `deepfilternet2`
2022-07-30 16:34:08 | INFO     | DF | Found checkpoint ../opt/conda/lib/python3.7/site-packages/pretrained_models/DeepFilterNet2/checkpoints/model_96.ckpt.best with epoch 96
2022-07-30 16:34:08 | WARNING  | DF | Unexpected key: erb_comp.c
2022-07-30 16:34:08 | WARNING  | DF | Unexpected key: erb_comp.mn
2022-07-30 16:34:08 | INFO     | DF | Model loaded
2022-07-30 16:34:09 | WARNING  | DF | Audio sampling rate does not match model sampling rate (32000, 48000). Resampling...
Traceback (most recent call last):
  File "/opt/conda/bin/deepFilter", line 8, in <module>
    sys.exit(run())
  File "/opt/conda/lib/python3.7/site-packages/df/enhance.py", line 329, in run
    main(parser.parse_args())
  File "/opt/conda/lib/python3.7/site-packages/df/enhance.py", line 44, in main
    model, df_state, audio, pad=args.compensate_delay, atten_lim_db=args.atten_lim
  File "/opt/conda/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/df/enhance.py", line 243, in enhance
    enhanced = model(spec, erb_feat, spec_feat)[0].cpu()
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/df/deepfilternet2.py", line 432, in forward
    e0, e1, e2, e3, emb, c0, lsnr = self.enc(feat_erb, feat_spec)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/df/deepfilternet2.py", line 173, in forward
    c0 = self.df_conv0(feat_spec)  # [B, C, T, Fc]
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/container.py", line 139, in forward
    input = module(input)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 457, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 454, in _conv_forward
    self.padding, self.dilation, self.groups)
RuntimeError: Expected canUse32BitIndexMath(input) && canUse32BitIndexMath(output) to be true, but got false.  (Could this error message be improved?  If so, please report an enhancement request to PyTorch.)
```

I did make [some modifications](https://github.com/Rikorose/DeepFilterNet/compare/main...youssefabdelm:DeepFilterNetColab:main) to the code so it still works with the Python 3.7 environment provided on the GPU cloud (however I noticed you made some changes since then so it could be that there's an issue there as well because I'm essentially doing `!pip install deepfilternet` / installing as instructed on readmethen replacing the corresponding files with the files I edited: `deepfilternet2.py`,`logger.py`,`multiframe.py` ) but it still works with less than 50 min files. This error shows up both on the A100 80 GB and A6000 48 GB, so I don't think it's due to memory limits. The 48GB A6000 was able to denoise a 50-minute wav file and failed on a longer than hour file. A100, when given the longer than hour file gave the same exact error above. 

Would love any help, no pressure whatssoever though!

**Comment by Rikorose** [comment]
Your tensors are too big, see: https://github.com/pytorch/pytorch/issues/80020

**Comment by youssefabdelm** [comment]
Ah I see, is a smaller audio length the only solution? I'd prefer to avoid splitting the audio file up before processing.

**Comment by youssefabdelm** [comment]
In the issue linked, OP mentioned:
> Now the code of canUse32BitIndexMath can be found in ATen/native/IndexingUtils.cpp, and simply checks whether the number of elements or an "offset" is greater than the size of int32_t. Naturally this is the case neither for the matrix above nor for the eventual Conv2D output.

Does that mean that all I need to do is increase the offset that he refers to of int32_t?

**Comment by Rikorose** [comment]
I currently don't see a way to process these large audio files

**Comment by youssefabdelm** [comment]
Ah no worries.
