### ISSUE TITLE
Numpy Array Error

### ISSUE THREAD

**Issue by Curlypla** [Rikorose/DeepFilterNet#125]
OS : Windows 11
Python version tested : 3.8 & 3.9

I tested on the different versions of pytorch but I always have this error

```
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Development\Environment\deepfilternet\Scripts\deepFilter.exe\__main__.py", line 7, in <module>
  File "c:\development\environment\deepfilternet\lib\site-packages\df\enhance.py", line 348, in run
    main(parser.parse_args())
  File "c:\development\environment\deepfilternet\lib\site-packages\df\enhance.py", line 42, in main
    audio = enhance(
  File "c:\development\environment\deepfilternet\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "c:\development\environment\deepfilternet\lib\site-packages\df\enhance.py", line 238, in enhance
    spec, erb_feat, spec_feat = df_features(audio, df_state, nb_df, device=get_device())
  File "c:\development\environment\deepfilternet\lib\site-packages\df\enhance.py", line 148, in df_features
    spec = df.analysis(audio.numpy())  # [C, Tf] -> [C, Tf, F]
RuntimeError: [df] Input array empty or not contiguous.
```

**Comment by Rikorose** [comment]
Hi, could you send me the audio or give me some more infos about the audio to reproduce your issue?

**Comment by Curlypla** [comment]
Audio : https://vocaroo.com/embed/1k1djcjE5qF3?autoplay
work perfectly in huggingface

**Comment by Rikorose** [comment]
Could you try latest master to see if it works now?

**Comment by Curlypla** [comment]
It works! I was using the compiled version so I don't know if it's because of the fix that it works

**Comment by surfingnirvana** [comment]
I also have this issue.

**Comment by Curlypla** [comment]
![image](https://user-images.githubusercontent.com/98696775/185453667-0cb332b4-bffd-4e9c-ae50-b2a9424a4159.png)
I followed the tutorial to compile it myself

**Comment by Rikorose** [comment]
I will try to release a next version by next week, which would include the fix.
