### ISSUE TITLE
All Cargo Tests pass, but train.py returns error 

### ISSUE THREAD

**Issue by Student204161** [Rikorose/DeepFilterNet#182]
I have been struggling with the same error for a while now...

I am using a conda environment in linux on a HPC solution. I previously had problems with Rust detecting multiple versions of HDF5 and (I think) I fixed it by defining HDF5_VERSION being the same as library and header (version 1.10.6) and HDF5_DIR as conda environment root. Following the instructions on https://github.com/aldanor/hdf5-rust, I also do

$ conda env config vars set RUSTFLAGS="-C link-args=-Wl,-rpath,$HDF5_DIR/lib"

And add the directory to path:
$ conda develop /zhome/a7/0/155527/Desktop/s204161/DEEPL_PLS/DeepFilterNet-main/DeepFilterNet/
 
Doing this, I manage to succesfully pass the cargo tests (It no longer complains about HDF5 version used by rust not being the same as the one in h5py):

(DEEPL_PLS) cargo test
    Finished test [optimized + debuginfo] target(s) in 2.06s
     Running unittests src/lib.rs (target/debug/deps/libdfdata-beeffcf7e03d4848)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running unittests src/lib.rs (target/debug/deps/libdf-9cd65e9fa81eadda)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running unittests src/lib.rs (target/debug/deps/deep_filter_ladspa-c16148d79da4c5bf)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running unittests src/lib.rs (target/debug/deps/df-f01c984070e59647)

running 30 tests
test reexport_dataset_modules::dataset::tests::test_hdf5_slice::case_06 - should panic ... ok
test reexport_dataset_modules::dataset::tests::test_hdf5_slice::case_05 - should panic ... ok
test tests::test_erb_inout ... ok
test reexport_dataset_modules::dataset::tests::test_mix_audio_signal ... ok
test reexport_dataset_modules::dataset::tests::test_hdf5_slice::case_07 - should panic ... ok
test transforms::tests::test_find_max_abs ... ok
test reexport_dataset_modules::augmentations::tests::test_rand_resample ... ok
test transforms::tests::test_stft_istft_delay ... ok
test reexport_dataset_modules::augmentations::tests::test_low_pass ... ok
test reexport_dataset_modules::augmentations::tests::test_clipping ... ok
test reexport_dataset_modules::dataset::tests::test_hdf5_slice::case_10 ... ok
test reexport_dataset_modules::dataset::tests::test_hdf5_read_pcm ... ok
test reexport_dataset_modules::dataset::tests::test_hdf5_slice::case_04 - should panic ... ok
test reexport_dataset_modules::dataset::tests::test_hdf5_slice::case_02 ... ok
test reexport_dataset_modules::dataset::tests::test_hdf5_slice::case_01 ... ok
test reexport_dataset_modules::dataset::tests::test_hdf5_slice::case_03 ... ok
test reexport_dataset_modules::augmentations::tests::test_gen_noise ... ok
test reexport_dataset_modules::dataset::tests::test_hdf5_slice::case_08 ... ok
test reexport_dataset_modules::dataset::tests::test_hdf5_slice::case_09 ... ok
test transforms::tests::test_ext_bandwidth_spectral ... ok
test reexport_dataset_modules::augmentations::tests::test_reverb ... ok
test reexport_dataset_modules::dataset::tests::test_fft_dataset ... ok
test reexport_dataset_modules::augmentations::tests::test_filters ... ok
test reexport_dataset_modules::augmentations::tests::test_compose ... ok
test reexport_dataset_modules::dataset::tests::test_td_dataset ... ok
test reexport_dataset_modules::dataset::tests::test_hdf5_read_flac ... ok
test transforms::tests::test_estimate_bandwidth ... ok
test reexport_dataset_modules::augmentations::tests::test_air_absorption ... ok
test reexport_dataset_modules::dataset::tests::test_hdf5_read_vorbis ... ok
test reexport_dataset_modules::dataloader::tests::test_data_loader ... ok

test result: ok. 30 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 6.37s

   Doc-tests df

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

**However when I cd into the repo and run for training it gives the error**

python DeepFilterNet/df/train.py /work3/s204161/config.cfg /work3/s204161/formatted_data/ /zhome/a7/0/155527/Desktop/s204161/DEEPL_PLS/DeepFilterNet/ --debug
2022-11-21 05:42:10 | INFO     | df.logger:init_logger:44 | Running on torch 1.12.0
2022-11-21 05:42:10 | INFO     | df.logger:init_logger:45 | Running on host n-62-27-19
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
2022-11-21 05:42:10 | INFO     | df.logger:init_logger:67 | Loading model settings of DeepFilterNet
2022-11-21 05:42:10 | INFO     | __main__:main:94 | Running on device cpu
2022-11-21 05:42:10 | INFO     | df.model:init_model:21 | Initializing model `deepfilternet3`
2022-11-21 05:42:10 | INFO     | libdfdata.torch_dataloader:__init__:99 | Initializing dataloader with data directory /work3/s204161/formatted_data/
2022-11-21 05:42:10 | ERROR    | __main__:<module>:633 | An error has been caught in function '<module>', process 'MainProcess' (16810), thread 'MainThread' (139678983296832):
Traceback (most recent call last):

> File "/zhome/a7/0/155527/Desktop/s204161/DEEPL_PLS/DeepFilterNet-main/DeepFilterNet/df/train.py", line 633, in <module>
    main()
    └ <function main at 0x7f08f2c37b50>

  File "/zhome/a7/0/155527/Desktop/s204161/DEEPL_PLS/DeepFilterNet-main/DeepFilterNet/df/train.py", line 139, in main
    dataloader = DataLoader(
                 └ <class 'libdfdata.torch_dataloader.PytorchDataLoader'>

  File "/zhome/a7/0/155527/ENTER/envs/DEEPL_PLS/lib/python3.10/site-packages/libdfdata/torch_dataloader.py", line 101, in __init__
    self.loader = _FdDataLoader(
    │             └ <class 'builtins._FdDataLoader'>
    └ <libdfdata.torch_dataloader.PytorchDataLoader object at 0x7f08f1dc6b60>

RuntimeError: DF dataset error: Hdf5ErrorDetail { source: H5Fopen(): unable to open file: bad superblock version number, msg: "Error during File::open of dataset /work3/s204161/formatted_data/VALID_SET_SPEECH.hdf5" }
(DEEPL_PLS)

**Comment by Rikorose** [comment]
Have you build the python wrapper (via `maturin develop`) with the rustc flags?

**Comment by Student204161** [comment]
Thanks for the quick response. 

That seems to be it! I just downgraded PyTorch and reran maturin develop and the data loads in. 

I am fairly sure I did build the python wrapper using maturin develop, but my guess is that I did things in the wrong order - I set the rustc flags after running maturin develop.

However I run into another error after what seems to be between 100-200 iterations...


(DEEPL_PLS) python DeepFilterNet/df/train.py /work3/s204161/config.cfg /work3/s204161/formatted_data/ /zhome/a7/0/155527/Desktop/s204161/DEEPL_PLS/DeepFilterNet-main/ --debug 
2022-11-21 07:58:29 | INFO     | df.logger:init_logger:44 | Running on torch 1.11.0
2022-11-21 07:58:29 | INFO     | df.logger:init_logger:45 | Running on host n-62-27-19
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
2022-11-21 07:58:30 | INFO     | df.logger:init_logger:67 | Loading model settings of DeepFilterNet-main
2022-11-21 07:58:30 | INFO     | __main__:main:94 | Running on device cpu
2022-11-21 07:58:30 | INFO     | df.model:init_model:21 | Initializing model `deepfilternet3`
2022-11-21 07:58:30 | INFO     | libdfdata.torch_dataloader:__init__:99 | Initializing dataloader with data directory /work3/s204161/formatted_data/
2022-11-21 07:58:30 | INFO     | libdfdata.torch_dataloader:df:hdf5_key_cache:20 | Loading HDF5 key cache from /work3/s204161/.cache_config.cfg
2022-11-21 07:58:30 | DEBUG    | libdfdata.torch_dataloader:df:dataset:591 | Opened Speech valid dataset /work3/s204161/formatted_data/VALID_SET_SPEECH.hdf5 with 2045 samples
2022-11-21 07:58:30 | DEBUG    | libdfdata.torch_dataloader:df:dataset:591 | Opened Noise valid dataset /work3/s204161/formatted_data/VALID_SET_NOISE.hdf5 with 742 samples
2022-11-21 07:58:30 | DEBUG    | libdfdata.torch_dataloader:df:dataset:591 | Opened RIR valid dataset /work3/s204161/formatted_data/VALID_SET_RIR.hdf5 with 1349 samples
2022-11-21 07:58:30 | DEBUG    | libdfdata.torch_dataloader:df:dataset:591 | Opened Speech train dataset /work3/s204161/formatted_data/TRAIN_SET_SPEECH.hdf5 with 1314 samples
2022-11-21 07:58:30 | DEBUG    | libdfdata.torch_dataloader:df:dataset:591 | Opened Noise train dataset /work3/s204161/formatted_data/TRAIN_SET_NOISE.hdf5 with 5395 samples
2022-11-21 07:58:30 | DEBUG    | libdfdata.torch_dataloader:df:dataset:591 | Opened RIR train dataset /work3/s204161/formatted_data/TRAIN_SET_RIR.hdf5 with 1349 samples
2022-11-21 07:58:30 | DEBUG    | libdfdata.torch_dataloader:df:dataset:591 | Opened Speech test dataset /work3/s204161/formatted_data/TEST_SET_SPEECH.hdf5 with 44242 samples
2022-11-21 07:58:30 | DEBUG    | libdfdata.torch_dataloader:df:dataset:591 | Opened Noise test dataset /work3/s204161/formatted_data/TEST_SET_NOISE.hdf5 with 256 samples
2022-11-21 07:58:30 | DEBUG    | libdfdata.torch_dataloader:df:dataset:591 | Opened RIR test dataset /work3/s204161/formatted_data/TEST_SET_RIR.hdf5 with 1349 samples
2022-11-21 07:58:30 | DEBUG    | __main__:load_opt:512 | Training with optimizer AdamW (
Parameter Group 0
    amsgrad: True
    betas: [0.9, 0.999]
    eps: 1e-08
    lr: 0.0005
    maximize: False
    weight_decay: 0.05
)
2022-11-21 07:58:30 | DEBUG    | df.logger:log_model_summary:178 | Failed to import ptflops. Cannot print model summary.
2022-11-21 07:58:30 | DEBUG    | df.config:save:77 | Config not modified. No need to overwrite on disk.
2022-11-21 07:58:30 | INFO     | __main__:run_epoch:335 | Start train epoch 0 with batch size 1
2022-11-21 07:58:30 | DEBUG    | libdfdata.torch_dataloader:df:dataset:1102 | No energy found in noise chime_partition1_chime_home_chunks_CR_lounge_200110_1601.s3900_chunk34.48kHz.wav, ds /work3/s204161/formatted_data/TRAIN_SET_NOISE.hdf5
2022-11-21 07:58:31 | INFO     | df.logger:log_metrics:148 | [0] [   0/2627] | loss:  0.18621 | LocalSnrLoss:  0.18621 | sdr_snr_0: -10.38411 | stoi_snr_0:  0.48016 | lr:  1.000E-04
2022-11-21 07:58:44 | DEBUG    | libdfdata.torch_dataloader:df:dataset:1102 | No energy found in noise chime_partition1_chime_home_chunks_CR_lounge_200110_1601.s3900_chunk48.48kHz.wav, ds /work3/s204161/formatted_data/TRAIN_SET_NOISE.hdf5
2022-11-21 07:59:14 | DEBUG    | libdfdata.torch_dataloader:df:dataset:1102 | No energy found in noise chime_partition1_chime_home_chunks_CR_lounge_200110_1601.s3900_chunk24.48kHz.wav, ds /work3/s204161/formatted_data/TRAIN_SET_NOISE.hdf5
2022-11-21 07:59:27 | INFO     | df.logger:log_metrics:148 | [0] [ 100/2627] | loss:  0.16598 | LocalSnrLoss:  0.07319 | sdr_snr_-5: -15.07572 | stoi_snr_-5:  0.38845 | sdr_snr_0: -9.85745 | stoi_snr_0:  0.54005 | sdr_snr_5: -12.70455 | stoi_snr_5:  0.62735 | sdr_snr_10: -8.17080 | stoi_snr_10:  0.62499 | sdr_snr_20: -7.52373 | stoi_snr_20:  0.68978 | sdr_snr_40: -12.03335 | stoi_snr_40:  0.31112 | lr:  1.051E-04
thread '<unnamed>' panicked at 'assertion failed: k <= self.len()', /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/slice/mod.rs:3056:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2022-11-21 07:59:36 | DEBUG    | libdfdata.torch_dataloader:df:dataset:1102 | No energy found in noise chime_partition1_chime_home_chunks_CR_lounge_200110_1601.s3900_chunk34.48kHz.wav, ds /work3/s204161/formatted_data/TRAIN_SET_NOISE.hdf5
2022-11-21 07:59:36 | ERROR    | __main__:<module>:633 | An error has been caught in function '<module>', process 'MainProcess' (7817), thread 'MainThread' (140135637280576):
Traceback (most recent call last):

> File "/zhome/a7/0/155527/Desktop/s204161/DEEPL_PLS/DeepFilterNet-main/DeepFilterNet/df/train.py", line 633, in <module>
    main()
    └ <function main at 0x7f7302820820>

  File "/zhome/a7/0/155527/Desktop/s204161/DEEPL_PLS/DeepFilterNet-main/DeepFilterNet/df/train.py", line 243, in main
    train_loss = run_epoch(
                 └ <function run_epoch at 0x7f73028215a0>

  File "/zhome/a7/0/155527/Desktop/s204161/DEEPL_PLS/DeepFilterNet-main/DeepFilterNet/df/train.py", line 350, in run_epoch
    for i, batch in enumerate(loader.iter_epoch(split, seed)):
        │  │                  │      │          │      └ 0
        │  │                  │      │          └ 'train'
        │  │                  │      └ <function PytorchDataLoader.iter_epoch at 0x7f73028213f0>
        │  │                  └ <libdfdata.torch_dataloader.PytorchDataLoader object at 0x7f73018358a0>
        │  └ Batch of size 1:
        │        SNRs: 5
        │        Gains: 0
        │    
        └ 116

  File "/zhome/a7/0/155527/ENTER/envs/DEEPL_PLS/lib/python3.10/site-packages/libdfdata/torch_dataloader.py", line 265, in iter_epoch
    batch = self._get_batch()
            │    └ <function PytorchDataLoader._get_batch at 0x7f73028212d0>
            └ <libdfdata.torch_dataloader.PytorchDataLoader object at 0x7f73018358a0>
  File "/zhome/a7/0/155527/ENTER/envs/DEEPL_PLS/lib/python3.10/site-packages/libdfdata/torch_dataloader.py", line 222, in _get_batch
    _, batch = self.data_queue.get()
               │    │          └ <function PytorchDataLoader._get_worker_queue_dummy.<locals>._Queue.get at 0x7f7301804820>
               │    └ <libdfdata.torch_dataloader.PytorchDataLoader._get_worker_queue_dummy.<locals>._Queue object at 0x7f7301834b50>
               └ <libdfdata.torch_dataloader.PytorchDataLoader object at 0x7f73018358a0>
  File "/zhome/a7/0/155527/ENTER/envs/DEEPL_PLS/lib/python3.10/site-packages/libdfdata/torch_dataloader.py", line 204, in get
    self.loader.cleanup()
    │    │      └ <method 'cleanup' of 'builtins._FdDataLoader' objects>
    │    └ <builtins._FdDataLoader object at 0x7f7301b59e40>
    └ <libdfdata.torch_dataloader.PytorchDataLoader object at 0x7f73018358a0>

RuntimeError: DF dataloader error: ThreadJoinError("Any { .. }")

**Comment by Rikorose** [comment]
Hm not sure where the error is. There is somewhere in `get_sample()` a slice out of bounce.

**Comment by Rikorose** [comment]
Could you try #183 with `maturin develop --features=timings -m pyDF-data/Cargo.toml` and train with `--log-level=TRACE`:

` python DeepFilterNet/df/train.py /work3/s204161/config.cfg /work3/s204161/formatted_data/ /zhome/a7/0/155527/Desktop/s204161/DEEPL_PLS/DeepFilterNet-main/ --log-level=TRACE `

**Comment by Student204161** [comment]
I raised the sampling factor from being very low to somewhat higher and I haven't run into that error again. I haven't partitioned my data properly yet and included it neatly, so it is very skewed.
Linux won't let me install:
![billede](https://user-images.githubusercontent.com/97975723/203034626-47d4e0fc-ace3-48cc-987a-6a1c20a4d9a7.png)

I can get it to train on cpu (I've ran for some epochs) but when I send it as a batch job to the cluster I get another error ;p 
![billede](https://user-images.githubusercontent.com/97975723/203034948-e695498d-3a45-4876-9c2f-29145ce6dc2f.png)

**Comment by Student204161** [comment]
I am using pytorch 1.11.0. 
I defined the local repository to be a git repo and now it only displays

![billede](https://user-images.githubusercontent.com/97975723/203140239-a1589eeb-13b6-4bca-a2c4-43fe490b0563.png)
While the output before the error is,
![billede](https://user-images.githubusercontent.com/97975723/203140604-9a4fcf75-63d5-42ec-b2ae-573df4dc2705.png)

From what I can find on the internet, the error has something to do with git,  I find it quite odd since I am still able to use git-terminal in the batch job.... I will keep trying to find the problem.
![billede](https://user-images.githubusercontent.com/97975723/203141047-de931045-e254-4aa7-bb66-6c209a70645b.png)

**Comment by Student204161** [comment]
Can I ask what pytorch version this framework is currently built on? Earlier I had installed pytorch=1.12.x but downgraded to 1.11.0 since I was worried about compatibility issues after reading through this thread: https://github.com/Rikorose/DeepFilterNet/issues/146#issuecomment-1269901621

**Comment by Student204161** [comment]
okay, I can see that you are right, I can see that pin_memory_loop() takes 5 arguments in python 1.13 while it was 4 in pytorch 1.11

https://github.com/pytorch/pytorch/blob/8d365ae9402179399e49090f1523bf33bea6ba3a/torch/utils/data/_utils/pin_memory.py#L17

https://github.com/pytorch/pytorch/blob/58a74f34f981de2c24b8f57c37687421c87a782a/torch/utils/data/_utils/pin_memory.py#L17

Thanks for all the help, I appreciate it very much.  Huge kudos for your help and enthusiasm, I wasn't expecting a reply within less than an hour of posting my issue this morning, you're a champ @Rikorose  🙌 🎉 😄
