### ISSUE TITLE
RuntimeError: CUDA error: out of memory / Segmentation fault | Batch training on cuda

### ISSUE THREAD

**Issue by KristianMoellmann** [Rikorose/DeepFilterNet#194]
Hi!

I've run into an issue when training a model on Windows Subsystem for Linux (WSL) using cuda and batch training.

I encounter the problem when using a batch size> 4. 

When using torch version <= 1.12.1 I get the following error:

```(venv) kristian:.../DeepFilterNet/DeepFilterNet$ python df/train.py --debug dataset.cfg "/mnt/e/data_dir/" base_dir_full_data_batch_schedule/
2022-11-25 17:46:05 | INFO     | df.logger:init_logger:44 | Running on torch 1.12.1+cu116
2022-11-25 17:46:05 | INFO     | df.logger:init_logger:45 | Running on host DESKTOP-E62J135
2022-11-25 17:46:05 | INFO     | df.logger:init_logger:48 | Git commit: bc6bd91, branch: main
2022-11-25 17:46:05 | INFO     | df.logger:init_logger:67 | Loading model settings of base_dir_full_data_batch_schedule
2022-11-25 17:46:06 | INFO     | __main__:main:94 | Running on device cuda:0
2022-11-25 17:46:06 | INFO     | df.model:init_model:21 | Initializing model `deepfilternet3`
2022-11-25 17:46:15 | INFO     | libdfdata.torch_dataloader:__init__:99 | Initializing dataloader with data directory /mnt/e/data_dir/
2022-11-25 17:46:16 | INFO     | libdfdata.torch_dataloader:df:hdf5_key_cache:20 | Loading HDF5 key cache from .cache_dataset.cfg
2022-11-25 17:46:16 | DEBUG    | libdfdata.torch_dataloader:df:dataset:591 | Opened Noise train dataset /mnt/e/data_dir/TRAIN_SET_NOISE.hdf5 with 1320 samples
2022-11-25 17:46:16 | DEBUG    | libdfdata.torch_dataloader:df:dataset:591 | Opened Speech test dataset /mnt/e/data_dir/TEST_SET_SPEECH.hdf5 with 12784 samples
2022-11-25 17:46:16 | DEBUG    | libdfdata.torch_dataloader:df:dataset:591 | Opened RIR test dataset /mnt/e/data_dir/TEST_SET_RIR.hdf5 with 1612 samples
2022-11-25 17:46:16 | DEBUG    | libdfdata.torch_dataloader:df:dataset:591 | Opened Noise test dataset /mnt/e/data_dir/TEST_SET_NOISE.hdf5 with 320 samples
2022-11-25 17:46:16 | DEBUG    | libdfdata.torch_dataloader:df:dataset:591 | Opened Speech valid dataset /mnt/e/data_dir/VALID_SET_SPEECH.hdf5 with 12526 samples
2022-11-25 17:46:16 | DEBUG    | libdfdata.torch_dataloader:df:dataset:591 | Opened Noise valid dataset /mnt/e/data_dir/VALID_SET_NOISE.hdf5 with 320 samples
2022-11-25 17:46:16 | DEBUG    | libdfdata.torch_dataloader:df:dataset:591 | Opened RIR valid dataset /mnt/e/data_dir/VALID_SET_RIR.hdf5 with 989 samples
2022-11-25 17:46:16 | DEBUG    | libdfdata.torch_dataloader:df:dataset:591 | Opened Speech train dataset /mnt/e/data_dir/TRAIN_SET_SPEECH.hdf5 with 61374 samples
2022-11-25 17:46:16 | DEBUG    | libdfdata.torch_dataloader:df:dataset:591 | Opened RIR train dataset /mnt/e/data_dir/TRAIN_SET_RIR.hdf5 with 4087 samples
2022-11-25 17:46:16 | DEBUG    | __main__:load_opt:512 | Training with optimizer AdamW (
Parameter Group 0
    amsgrad: True
    betas: [0.9, 0.999]
    capturable: False
    eps: 1e-08
    foreach: None
    lr: 0.0005
    maximize: False
    weight_decay: 0.05
)
2022-11-25 17:46:16 | DEBUG    | df.logger:log_model_summary:178 | Failed to import ptflops. Cannot print model summary.
2022-11-25 17:46:16 | DEBUG    | df.config:save:77 | Config not modified. No need to overwrite on disk.
2022-11-25 17:46:16 | INFO     | __main__:run_epoch:335 | Start train epoch 0 with batch size 5
2022-11-25 17:46:24 | INFO     | df.logger:log_metrics:148 | [0] [    0/12274] | loss:  0.17455 | LocalSnrLoss:  0.17455 | sdr_snr_-5: -14.50533 | stoi_snr_-5:  0.48780 | sdr_snr_0: -9.15027 | stoi_snr_0:  0.67690 | sdr_snr_10: -11.32550 | stoi_snr_10:  0.50960 | sdr_snr_20: -14.79081 | stoi_snr_20:  0.66063 | sdr_snr_40: -9.94032 | stoi_snr_40:  0.73023 | lr:  1.000E-04
2022-11-25 17:46:27 | ERROR    | __main__:<module>:633 | An error has been caught in function '<module>', process 'MainProcess' (354), thread 'MainThread' (139636015847232):
Traceback (most recent call last):

> File "df/train.py", line 633, in <module>
    main()
    └ <function main at 0x7eff7a6eb8b0>

  File "df/train.py", line 243, in main
    train_loss = run_epoch(
                 └ <function run_epoch at 0x7eff7a6f35e0>

  File "df/train.py", line 350, in run_epoch
    for i, batch in enumerate(loader.iter_epoch(split, seed)):
        │  │                  │      │          │      └ 0
        │  │                  │      │          └ 'train'
        │  │                  │      └ <function PytorchDataLoader.iter_epoch at 0x7eff7a6f33a0>
        │  │                  └ <libdfdata.torch_dataloader.PytorchDataLoader object at 0x7efefd870e50>
        │  └ Batch of size 5:
        │        SNRs: 0,40,0,10,-5
        │        Gains: 0,0,6,6,0
        │
        └ 32

  File "/mnt/d/DeepFilterNet/env/venv/lib/python3.8/site-packages/libdfdata/torch_dataloader.py", line 259, in iter_epoch
    batch = self._get_batch()
            │    └ <function PytorchDataLoader._get_batch at 0x7eff7a6f3280>
            └ <libdfdata.torch_dataloader.PytorchDataLoader object at 0x7efefd870e50>
  File "/mnt/d/DeepFilterNet/env/venv/lib/python3.8/site-packages/libdfdata/torch_dataloader.py", line 224, in _get_batch
    batch.reraise()
    │     └ <function ExceptionWrapper.reraise at 0x7eff875068b0>
    └ <torch._utils.ExceptionWrapper object at 0x7efef133c9a0>
  File "/mnt/d/DeepFilterNet/env/venv/lib/python3.8/site-packages/torch/_utils.py", line 461, in reraise
    raise exception
          └ RuntimeError('Caught RuntimeError in pin memory thread for device 0.\nOriginal Traceback (most recent call last):\n  File "/m...

RuntimeError: Caught RuntimeError in pin memory thread for device 0.
Original Traceback (most recent call last):
  File "/mnt/d/DeepFilterNet/env/venv/lib/python3.8/site-packages/torch/utils/data/_utils/pin_memory.py", line 34, in _pin_memory_loop
    data = pin_memory(data, device)
  File "/mnt/d/DeepFilterNet/env/venv/lib/python3.8/site-packages/torch/utils/data/_utils/pin_memory.py", line 70, in pin_memory
    return data.pin_memory()
  File "/mnt/d/DeepFilterNet/env/venv/lib/python3.8/site-packages/libdfdata/torch_dataloader.py", line 44, in pin_memory
    self.speech = self.speech.pin_memory()
RuntimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
```

While using using Torch version 1.13 I simply get a segmentation fault:

```
(venv) kristian:.../DeepFilterNet/DeepFilterNet$ python df/train.py --debug dataset.cfg "/mnt/e/data_dir/" base_dir_full_data_batch_schedule/
2022-11-25 16:11:32 | INFO     | df.logger:init_logger:44 | Running on torch 1.13.0+cu117
2022-11-25 16:11:32 | INFO     | df.logger:init_logger:45 | Running on host DESKTOP-E62J135
2022-11-25 16:11:32 | INFO     | df.logger:init_logger:48 | Git commit: bc6bd91, branch: main
2022-11-25 16:11:32 | INFO     | df.logger:init_logger:67 | Loading model settings of base_dir_full_data_batch_schedule
2022-11-25 16:11:32 | INFO     | __main__:main:94 | Running on device cuda:0
2022-11-25 16:11:32 | INFO     | df.model:init_model:21 | Initializing model `deepfilternet3`
2022-11-25 16:11:43 | INFO     | libdfdata.torch_dataloader:__init__:99 | Initializing dataloader with data directory /mnt/e/data_dir/
2022-11-25 16:11:43 | INFO     | libdfdata.torch_dataloader:df:hdf5_key_cache:20 | Loading HDF5 key cache from .cache_dataset.cfg
2022-11-25 16:11:43 | DEBUG    | libdfdata.torch_dataloader:df:dataset:591 | Opened Noise valid dataset /mnt/e/data_dir/VALID_SET_NOISE.hdf5 with 320 samples
2022-11-25 16:11:43 | DEBUG    | libdfdata.torch_dataloader:df:dataset:591 | Opened Noise test dataset /mnt/e/data_dir/TEST_SET_NOISE.hdf5 with 320 samples
2022-11-25 16:11:43 | DEBUG    | libdfdata.torch_dataloader:df:dataset:591 | Opened Noise train dataset /mnt/e/data_dir/TRAIN_SET_NOISE.hdf5 with 1320 samples
2022-11-25 16:11:43 | DEBUG    | libdfdata.torch_dataloader:df:dataset:591 | Opened Speech valid dataset /mnt/e/data_dir/VALID_SET_SPEECH.hdf5 with 12526 samples
2022-11-25 16:11:43 | DEBUG    | libdfdata.torch_dataloader:df:dataset:591 | Opened Speech test dataset /mnt/e/data_dir/TEST_SET_SPEECH.hdf5 with 12784 samples
2022-11-25 16:11:43 | DEBUG    | libdfdata.torch_dataloader:df:dataset:591 | Opened RIR valid dataset /mnt/e/data_dir/VALID_SET_RIR.hdf5 with 989 samples
2022-11-25 16:11:43 | DEBUG    | libdfdata.torch_dataloader:df:dataset:591 | Opened RIR test dataset /mnt/e/data_dir/TEST_SET_RIR.hdf5 with 1612 samples
2022-11-25 16:11:43 | DEBUG    | libdfdata.torch_dataloader:df:dataset:591 | Opened Speech train dataset /mnt/e/data_dir/TRAIN_SET_SPEECH.hdf5 with 61374 samples
2022-11-25 16:11:43 | DEBUG    | libdfdata.torch_dataloader:df:dataset:591 | Opened RIR train dataset /mnt/e/data_dir/TRAIN_SET_RIR.hdf5 with 4087 samples
2022-11-25 16:11:43 | DEBUG    | __main__:load_opt:512 | Training with optimizer AdamW (
Parameter Group 0
    amsgrad: True
    betas: [0.9, 0.999]
    capturable: False
    eps: 1e-08
    foreach: None
    lr: 0.0005
    maximize: False
    weight_decay: 0.05
)
2022-11-25 16:11:43 | DEBUG    | df.logger:log_model_summary:178 | Failed to import ptflops. Cannot print model summary.
2022-11-25 16:11:43 | DEBUG    | df.config:save:77 | Config not modified. No need to overwrite on disk.
2022-11-25 16:11:43 | INFO     | __main__:run_epoch:335 | Start train epoch 0 with batch size 5
Segmentation fault
```

When using batch size [1, 4], training seems to be going without problems. I intend to use batch size scheduling like that used in the DeepFilterNet 2 paper, so this problem is quite bothersome.

I'm training on a machine with an 8GB Nvidia RTX 2070 super and 32GB ram, so I wouldn't think that a batch size of 5 would be too much to handle, and according to Task Manager, nowhere near all of the dedicated GPU memory is being used.

Might I be doing something wrong, or is there an issue with the code?

Thank you for your time.

**Follow-up:**

I've tried explicitly setting `device = cpu` in the `config.ini` file, and the same problem still occurs. So maybe this doesn't have anything to do with cuda?

```
(venv) kristian:.../DeepFilterNet/DeepFilterNet$ python df/train.py dataset.cfg "/mnt/e/data_dir/" base_dir_full_data_patience15/
2022-11-26 12:06:24 | INFO     | DF | Running on torch 1.12.1+cu116
2022-11-26 12:06:24 | INFO     | DF | Running on host DESKTOP-E62J135
2022-11-26 12:06:24 | INFO     | DF | Git commit: bc6bd91, branch: main
2022-11-26 12:06:24 | INFO     | DF | Loading model settings of base_dir
2022-11-26 12:06:24 | INFO     | DF | Running on device cpu
2022-11-26 12:06:24 | INFO     | DF | Initializing model `deepfilternet3`
2022-11-26 12:06:24 | INFO     | DF | Initializing dataloader with data directory /mnt/e/data_dir/
2022-11-26 12:06:24 | INFO     | DF | Loading HDF5 key cache from .cache_dataset.cfg
2022-11-26 12:06:25 | INFO     | DF | Start train epoch 0 with batch size 5
2022-11-26 12:06:31 | INFO     | DF | [0] [    0/12274] | loss:  0.17458 | lr:  1.000E-04
2022-11-26 12:06:47 | ERROR    | DF | An error has been caught in function '<module>', process 'MainProcess' (273), thread 'MainThread' (139971533748032):
Traceback (most recent call last):

> File "df/train.py", line 633, in <module>
    main()
    └ <function main at 0x7f4d98db98b0>

  File "df/train.py", line 243, in main
    train_loss = run_epoch(
                 └ <function run_epoch at 0x7f4d98dc15e0>

  File "df/train.py", line 350, in run_epoch
    for i, batch in enumerate(loader.iter_epoch(split, seed)):
        │  │                  │      │          │      └ 0
        │  │                  │      │          └ 'train'
        │  │                  │      └ <function PytorchDataLoader.iter_epoch at 0x7f4d98dc13a0>
        │  │                  └ <libdfdata.torch_dataloader.PytorchDataLoader object at 0x7f4d1beeb250>
        │  └ Batch of size 5:
        │        SNRs: 0,40,0,10,-5
        │        Gains: 0,0,6,6,0
        │
        └ 32

  File "/mnt/d/DeepFilterNet/env/venv/lib/python3.8/site-packages/libdfdata/torch_dataloader.py", line 259, in iter_epoch
    batch = self._get_batch()
            │    └ <function PytorchDataLoader._get_batch at 0x7f4d98dc1280>
            └ <libdfdata.torch_dataloader.PytorchDataLoader object at 0x7f4d1beeb250>
  File "/mnt/d/DeepFilterNet/env/venv/lib/python3.8/site-packages/libdfdata/torch_dataloader.py", line 224, in _get_batch
    batch.reraise()
    │     └ <function ExceptionWrapper.reraise at 0x7f4da5bd48b0>
    └ <torch._utils.ExceptionWrapper object at 0x7f4d1aaba610>
  File "/mnt/d/DeepFilterNet/env/venv/lib/python3.8/site-packages/torch/_utils.py", line 461, in reraise
    raise exception
          └ RuntimeError('Caught RuntimeError in pin memory thread for device 0.\nOriginal Traceback (most recent call last):\n  File "/m...

RuntimeError: Caught RuntimeError in pin memory thread for device 0.
Original Traceback (most recent call last):
  File "/mnt/d/DeepFilterNet/env/venv/lib/python3.8/site-packages/torch/utils/data/_utils/pin_memory.py", line 34, in _pin_memory_loop
    data = pin_memory(data, device)
  File "/mnt/d/DeepFilterNet/env/venv/lib/python3.8/site-packages/torch/utils/data/_utils/pin_memory.py", line 70, in pin_memory
    return data.pin_memory()
  File "/mnt/d/DeepFilterNet/env/venv/lib/python3.8/site-packages/libdfdata/torch_dataloader.py", line 45, in pin_memory
    self.noisy = self.noisy.pin_memory()
RuntimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
```

**Comment by Rikorose** [comment]
Hm thats interesting. I cannot reproduce on my linux machine though. Maybe it is related to WSL. Usually, I see out of memory errors during forward/backward pass. Could you update to latest master and try again with `device=cpu`?

**Comment by KungFuKevin** [comment]
I, unfortunately, won't have time to test this out because of deadlines, but after some testing, it seems as if I'm able to train DeepFilterNet2 using a batch size of approximately 24. This feels more reasonable to me... 
What does DeepFilterNet3 do differently, or might something be off?
