### ISSUE TITLE
Group Shuffle parameter missed in the default config

### ISSUE THREAD

**Issue by gleb-shnshn** [Rikorose/DeepFilterNet#20]
Running `deepFilter wav_name`

```python3
Traceback (most recent call last):
  File "deepFilter", line 8, in <module>
    sys.exit(main())
  File "env/lib/python3.8/site-packages/df/enhance.py", line 66, in main
    p = ModelParams()
  File "env/lib/python3.8/site-packages/df/model.py", line 15, in __init__
    self.__params = getattr(import_module("df." + self.__model), "ModelParams")()
  File "env/lib/python3.8/site-packages/df/deepfilternet.py", line 48, in __init__
    self.group_shuffle: bool = config(
  File "env/lib/python3.8/site-packages/df/config.py", line 114, in __call__
    raise ValueError(f"Value '{option}' not found in config (defaults not allowed).")
ValueError: Value 'GROUP_SHUFFLE' not found in config (defaults not allowed).
```

**Comment by Rikorose** [comment]
Hi there, Thanks for your interest in DeepFilterNet and for reporting this bug. I just pushed a fix to main.

Can you try it e.g. using:
```bash
python -m pip install -U git+https://github.com/Rikorose/DeepFilterNet#subdirectory=DeepFilterNet
```

**Comment by gleb-shnshn** [comment]
Yes, it works, thank you
