### ISSUE TITLE
Atten-lim bug?

### ISSUE THREAD

**Issue by youssefabdelm** [Rikorose/DeepFilterNet#201]
When running on Colab (with `!deepFilter`) `--atten-lim` works fine. However, when running on Runpod (GPU cloud computing) on an A100, I get this error:

```
Traceback (most recent call last):
  File "/opt/conda/bin/deepFilter", line 8, in <module>
    sys.exit(run())
  File "/opt/conda/lib/python3.7/site-packages/df/enhance.py", line 329, in run
    main(parser.parse_args())
  File "/opt/conda/lib/python3.7/site-packages/df/enhance.py", line 44, in main
    model, df_state, audio, pad=args.compensate_delay, atten_lim_db=args.atten_lim
  File "/opt/conda/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/df/enhance.py", line 247, in enhance
    enhanced = as_complex(spec.squeeze(1)) * lim + enhanced * (1 - lim)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
```

Do I need to set the device somewhere?

**Comment by Rikorose** [comment]
Should be fixed on main soon
