### ISSUE TITLE
Converter to .onnx model

### ISSUE THREAD

**Issue by wangmou21** [Rikorose/DeepFilterNet#249]
Hi, I have installed monkeytype. However, I still have the same problem. #174

```
2023-02-06 22:33:43.807 | INFO     | __main__:export_impl:88 - Exporting model 'enc' to .\export
2023-02-06 22:33:43.809 | INFO     | __main__:export_impl:91 -   Input shapes: {'feat_erb': torch.Size([1, 1, 100, 32]), 'feat_spec': torch.Size([1, 2, 100, 96])}
2023-02-06 22:33:43.948 | INFO     | __main__:export_impl:95 -   Output shapes: {'e0': torch.Size([1, 64, 100, 32]), 'e1': torch.Size([1, 64, 100, 16]), 'e2': torch.Size([1, 64, 100, 8]), 'e3': torch.Size([1, 64, 100, 8]), 'emb': torch.Size([1, 100, 256]), 'c0': torch.Size([1, 64, 100, 96]), 'lsnr': torch.Size([1, 100, 1])}
Traceback (most recent call last):
  File "H:\work2023\DeepFilterNet-main\export.py", line 343, in <module>
    main(args)
  File "H:\work2023\DeepFilterNet-main\export.py", line 309, in main
    export(
  File "C:\Users\wangm\miniconda3\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "H:\work2023\DeepFilterNet-main\export.py", line 193, in export
    e0, e1, e2, e3, emb, c0, lsnr = export_impl(
  File "H:\work2023\DeepFilterNet-main\export.py", line 98, in export_impl
    model = torch.jit.script(model, example_inputs=[tuple(a for a in inputs)])
  File "C:\Users\wangm\miniconda3\lib\site-packages\torch\jit\_script.py", line 1286, in script
    return torch.jit._recursive.create_script_module(
  File "C:\Users\wangm\miniconda3\lib\site-packages\torch\jit\_recursive.py", line 476, in create_script_module
    return create_script_module_impl(nn_module, concrete_type, stubs_fn)
  File "C:\Users\wangm\miniconda3\lib\site-packages\torch\jit\_recursive.py", line 542, in create_script_module_impl
    create_methods_and_properties_from_stubs(concrete_type, method_stubs, property_stubs)
  File "C:\Users\wangm\miniconda3\lib\site-packages\torch\jit\_recursive.py", line 393, in create_methods_and_properties_from_stubs
    concrete_type._create_methods_and_properties(property_defs, property_rcbs, method_defs, method_rcbs, method_defaults)
RuntimeError: Unsupported value kind: Tensor
```

**Comment by Rikorose** [comment]
Which versions (DF, pytorch, monkeytype, etc) are you using?

**Comment by wangmou21** [comment]
Thanks! The packages I am using are as follows:
DF=0.4.0
PyTorch=1.13.1 (Cuda 11.7)
MonkeyType=22.2.0
onnx=1.13
I also tried PyTorch 2.0. The errors are the same.

**Comment by Rikorose** [comment]
I cannot reproduce your error

**Comment by 63liucan63** [comment]
Hello，I have encountered a similar problem and would like to know how you resolved it?

**Comment by 63liucan63** [comment]
Hello，I have encountered a similar problem and would like to know how you resolved it?

**Comment by hardikdgsa** [comment]
@Janne-byti @wangmou21 Can you please provide the steps if you are able to export to onnx model
