### ISSUE TITLE
Out of Memory

### ISSUE THREAD

**Issue by ctarter** [Rikorose/DeepFilterNet#265]
I am trying to clean up large audio files (50-100MB) and I keep getting out of memory errors. I tried both cpu and cuda. Ive tried lowering my batch size all the way down to 0. Nothing is working. Is there anyway to get around this?

BEFORE:
Max GPU memory usage: 0.0009765625 MB
Current GPU memory usage: 0.0009765625 MB

AFTER:
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 3.91 GiB (GPU 0; 8.00 GiB total capacity; 4.83 GiB already allocated; 2.03 GiB free; 4.84 GiB reserved in total by PyTorch)

**Comment by Rikorose** [comment]
The easiest way is to use the `deep-filter` binary which runs in a real-time loop. This requires minimal memory.

However, 50MB files should be denoisable via python and CPU processing. Are you sure that you did run on CPU?

Also
> BEFORE:
> Max GPU memory usage: 0.0009765625 MB
> Current GPU memory usage: 0.0009765625 MB

is probably not correct.

**Comment by ctarter** [comment]
I just ran a test via terminal 8mb audio file. 

corey@TarterTop:~/DeepFilterNet/DeepFilterNet/input2$ deepFilter ankenman-100_compressed.mp3 
2023-02-27 10:54:22 | INFO     | DF | Running on torch 1.13.1+cu117
2023-02-27 10:54:22 | INFO     | DF | Running on host *******
fatal: not a git repository (or any of the parent directories): .git
2023-02-27 10:54:22 | INFO     | DF | Loading model settings of DeepFilterNet2
2023-02-27 10:54:22 | INFO     | DF | Using DeepFilterNet2 model at /home/corey/.cache/DeepFilterNet/DeepFilterNet2
2023-02-27 10:54:22 | INFO     | DF | Initializing model `deepfilternet2`
2023-02-27 10:54:24 | INFO     | DF | Found checkpoint /home/corey/.cache/DeepFilterNet/DeepFilterNet2/checkpoints/model_96.ckpt.best with epoch 96
2023-02-27 10:54:24 | INFO     | DF | Running on device cuda:0
2023-02-27 10:54:24 | INFO     | DF | Model loaded
2023-02-27 10:54:26 | WARNING  | DF | Audio sampling rate does not match model sampling rate (32000, 48000). Resampling...
Traceback (most recent call last):
  File "/home/corey/.local/bin/deepFilter", line 8, in <module>
    sys.exit(run())
  File "/home/corey/.local/lib/python3.8/site-packages/df/enhance.py", line 308, in run
    main(args)
  File "/home/corey/.local/lib/python3.8/site-packages/df/enhance.py", line 43, in main
    audio = enhance(
  File "/home/corey/.local/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/corey/.local/lib/python3.8/site-packages/df/enhance.py", line 194, in enhance
    enhanced = model(spec.clone(), erb_feat, spec_feat)[0].cpu()
  File "/home/corey/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/corey/.local/lib/python3.8/site-packages/df/deepfilternet2.py", line 491, in forward
    e0, e1, e2, e3, emb, c0, lsnr = self.enc(feat_erb, feat_spec)
  File "/home/corey/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/corey/.local/lib/python3.8/site-packages/df/deepfilternet2.py", line 172, in forward
    e0 = self.erb_conv0(feat_erb)  # [B, C, T, F]
  File "/home/corey/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/corey/.local/lib/python3.8/site-packages/torch/nn/modules/container.py", line 204, in forward
    input = module(input)
  File "/home/corey/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/corey/.local/lib/python3.8/site-packages/torch/nn/modules/batchnorm.py", line 171, in forward
    return F.batch_norm(
  File "/home/corey/.local/lib/python3.8/site-packages/torch/nn/functional.py", line 2450, in batch_norm
    return torch.batch_norm(
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 2.98 GiB (GPU 0; 8.00 GiB total capacity; 6.45 GiB already allocated; 0 bytes free; 6.47 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by ctarter** [comment]
I think the problem is my audio is over an hour long. When i trim audio down to 1min it works fine, of course. But i need to process 800 files all around an hour in length. Any ideas how to accomplish this? I dont care how long it takes, ill just leave my computer running all night if needed.

**Comment by Rikorose** [comment]
I already provided solutions. First resample all your audio to 48kHz. Second, process the audio files using the deep-filter binary. You can do this e.g. using a bash script that loops over your files.

**Comment by yadalik** [comment]
I have 30-minutes long WAV's, stereo 48kHz, 16 bit, and GPU (GTX 1080, 8GB RAM) shows same error until I divide them in chunks by 6 minutes (~69MB each, but maybe 5 mins would be safer), in this case it did not extends limit about 7.5GB, and this, including ~200MB system load of GPU, let it to process WAV. The binary is not working for me now ( https://github.com/Rikorose/DeepFilterNet/issues/230#issuecomment-1547522499 ), and I like the speed of GPU. So:
1. Divide file in segments:
`ffmpeg -i input.wav -f segment -segment_time number_in_seconds segmented_%03d.wav`
2. Process segments with python script using something like 

```
input_files = glob.glob(os.path.join(base_dir, 'segmented*.wav'))
# load model
for input_file in input_file:
    # output_file = input_file.replace('.wav', '_enchanced.wav)
    # process and save input file
```

4. Combine them back `sox *enchanced.wav combined_back.wav`

P.S.: The only thing I concern and will investigate further, is how DeepFilterNet will work in case cutting file in the middle of word.

**Comment by zh-plus** [comment]
You can try to segment audio into chunks in code:
```python
audio, info = load_audio(audio_path, sr=df_state.sr())

# Split audio into 10min chunks
audio_chunks = [audio[:, i:i + 600 * info.sample_rate]
                for i in range(0, audio.shape[1], 600 * info.sample_rate)]

enhanced_chunks = []
for ac in audio_chunks:
    enhanced_chunks.append(enhance(model, df_state, ac, atten_lim_db=atten_lim_db))

enhanced = torch.cat(enhanced_chunks, dim=1)

assert enhanced.shape == audio.shape, 'Enhanced audio shape does not match original audio shape.'

save_audio(ns_path, enhanced, sr=df_state.sr())
```
