### ISSUE TITLE
torch 2.0 compat

### ISSUE THREAD

**Issue by yassinebelatar** [Rikorose/DeepFilterNet#285]
I have
cuda 12
torch                    2.0.0
torchaudio               2.0.1
Ubuntu i get this error 
Traceback (most recent call last):
  File "/usr/local/bin/deepFilter", line 5, in <module>
    from df.enhance import run
  File "/usr/local/lib/python3.10/dist-packages/df/enhance.py", line 13, in <module>
    from df.checkpoint import load_model as load_model_cp
  File "/usr/local/lib/python3.10/dist-packages/df/checkpoint.py", line 13, in <module>
    from df.utils import check_finite_module
  File "/usr/local/lib/python3.10/dist-packages/df/utils.py", line 13, in <module>
    from torch._six import string_classes
ModuleNotFoundError: No module named 'torch._six'

**Comment by Rikorose** [comment]
I have not tested with torch 2.0, probably some changes are required.

**Comment by mattpitkin** [comment]
I've tried to address this in https://github.com/Rikorose/DeepFilterNet/pull/287
