### ISSUE TITLE
NoDatasetFoundError

### ISSUE THREAD

**Issue by Porridge144** [Rikorose/DeepFilterNet#625]
Has anyone met this error when running the trainning script?

following is the command to start the training, and im using the sample dataset provided in the official repo under assets folder:

python df/train.py assets/dataset.cfg assets

2024-12-31 16:54:40 | ERROR    | __main__:<module>:630 | An error has been caught in function '<module>', process 'MainProcess' (60068), thread 'MainThread' (140480334067520):
Traceback (most recent call last):

> File "df/train.py", line 630, in <module>
    main()
    └ <function main at 0x7fc406670f70>

  File "df/train.py", line 143, in main
    dataloader = DataLoader(
                 └ <class 'libdfdata.torch_dataloader.PytorchDataLoader'>

  File "deep_filter_net/pyDF-data/libdfdata/torch_dataloader.py", line 104, in __init__
    self.loader = _FdDataLoader(
    │             └ <class 'builtins._FdDataLoader'>
    └ <libdfdata.torch_dataloader.PytorchDataLoader object at 0x7fc403eca610>

RuntimeError: DF dataset error: NoDatasetFoundError("Please check your dataset folder and configuration.")

**Comment by cweaver-logitech** [comment]
I'm also encounter this error. How did you resolve it?
